In [1]:
import numpy as np
import torch
import torch.nn as nn
from MnistLayers import Mul,Add,ReLU, Sigmoid, SoftMaxWithCrossEntropy, Linear
eps = 1e-8

In [2]:
X = np.full((10,5),2.)
W = np.full((5,),3.)
b = np.array([1,2,3,4])
X_tensor = torch.full((10,5),2., requires_grad=True)
W_tensor = torch.full((5,),3., requires_grad=True)
b_tensor= torch.tensor([1.,2.,3.,4.], requires_grad=True)

##### linear

In [3]:
X = np.full((10,5),2.)
X_tensor = torch.full((10,5),2., requires_grad=True)

In [4]:
model = Linear(5,3)
model_torch = nn.Linear(5,3)

Y = model.forward(X)
Y_tensor = model_torch(X_tensor)
print(Y)
print(Y_tensor)

[[-0.1337701   0.89626499  0.12284613]
 [-0.1337701   0.89626499  0.12284613]
 [-0.1337701   0.89626499  0.12284613]
 [-0.1337701   0.89626499  0.12284613]
 [-0.1337701   0.89626499  0.12284613]
 [-0.1337701   0.89626499  0.12284613]
 [-0.1337701   0.89626499  0.12284613]
 [-0.1337701   0.89626499  0.12284613]
 [-0.1337701   0.89626499  0.12284613]
 [-0.1337701   0.89626499  0.12284613]]
tensor([[ 0.1125,  0.2297, -1.6066],
        [ 0.1125,  0.2297, -1.6066],
        [ 0.1125,  0.2297, -1.6066],
        [ 0.1125,  0.2297, -1.6066],
        [ 0.1125,  0.2297, -1.6066],
        [ 0.1125,  0.2297, -1.6066],
        [ 0.1125,  0.2297, -1.6066],
        [ 0.1125,  0.2297, -1.6066],
        [ 0.1125,  0.2297, -1.6066],
        [ 0.1125,  0.2297, -1.6066]], grad_fn=<AddmmBackward0>)


In [5]:
dX,dW,db = model.backward(np.ones_like(Y))
Y_tensor.backward(torch.ones_like(Y_tensor))
print(dX)
print(X_tensor.grad)

[[ 0.16634097  0.18116754 -0.05391286  0.60599591 -0.45692103]
 [ 0.16634097  0.18116754 -0.05391286  0.60599591 -0.45692103]
 [ 0.16634097  0.18116754 -0.05391286  0.60599591 -0.45692103]
 [ 0.16634097  0.18116754 -0.05391286  0.60599591 -0.45692103]
 [ 0.16634097  0.18116754 -0.05391286  0.60599591 -0.45692103]
 [ 0.16634097  0.18116754 -0.05391286  0.60599591 -0.45692103]
 [ 0.16634097  0.18116754 -0.05391286  0.60599591 -0.45692103]
 [ 0.16634097  0.18116754 -0.05391286  0.60599591 -0.45692103]
 [ 0.16634097  0.18116754 -0.05391286  0.60599591 -0.45692103]
 [ 0.16634097  0.18116754 -0.05391286  0.60599591 -0.45692103]]
tensor([[-0.4327,  0.5525,  0.1700, -0.6020,  0.0203],
        [-0.4327,  0.5525,  0.1700, -0.6020,  0.0203],
        [-0.4327,  0.5525,  0.1700, -0.6020,  0.0203],
        [-0.4327,  0.5525,  0.1700, -0.6020,  0.0203],
        [-0.4327,  0.5525,  0.1700, -0.6020,  0.0203],
        [-0.4327,  0.5525,  0.1700, -0.6020,  0.0203],
        [-0.4327,  0.5525,  0.1700, -0.

##### SoftMax with CrossEntropy

In [6]:
class SMwtCE(nn.Module) :
    def __init__(self):
        super().__init__()
        self.Softmax = nn.Softmax(dim=1)
        self.Crossentropy = nn.CrossEntropyLoss()

    def forward(self, X, T) :
        X1 = self.Softmax(X)
        print(X1)
        Y = self.Crossentropy(X1,T)
        return Y

In [7]:
X = np.array([[0.,1.,-1.,3.],[0.5,0.7,0.,0.]])
X_tensor = torch.tensor([[0.,1.,-1.,3.],[0.5,0.7,0.,0.]], requires_grad=True)
T = np.array([[1., 0., 0., 0.],[0., 1., 0., 0.]])
T_tensor = torch.tensor([[1., 0., 0., 0.],[0., 1., 0., 0.]], requires_grad=True)

In [8]:
model = SoftMaxWithCrossEntropy()
model_torch = nn.CrossEntropyLoss()
Y = model.forward(X,T)
Y_tensor=model_torch(X_tensor,T_tensor)

print(Y)
print(Y_tensor)

2.1095215390499398
tensor(2.1095, grad_fn=<DivBackward1>)


In [9]:
dX = model.backward()
Y_tensor.backward(torch.ones_like(Y_tensor))
print(np.sum(dX))
print(X_tensor.grad)

1.1102230246251565e-16
tensor([[-0.4793,  0.0562,  0.0076,  0.4155],
        [ 0.1456, -0.3222,  0.0883,  0.0883]])


##### Sigmoid

In [10]:
X = np.array([[0,1,-1,3],[0.5,0.7,0,0]])
X_tensor = torch.tensor([[0.,1.,-1.,3.],[0.5,0.7,0.,0.]], requires_grad=True)

In [11]:
model = Sigmoid()
model_torch = nn.Sigmoid()

Y = model.forward(X)
Y_tensor = model_torch(X_tensor)
print(Y)
print(Y_tensor)

[[0.5        0.73105858 0.26894142 0.95257413]
 [0.62245933 0.66818777 0.5        0.5       ]]
tensor([[0.5000, 0.7311, 0.2689, 0.9526],
        [0.6225, 0.6682, 0.5000, 0.5000]], grad_fn=<SigmoidBackward0>)


In [12]:
dX = model.backward(np.ones_like(Y))
Y_tensor.backward(torch.ones_like(Y_tensor))
print(dX)
print(X_tensor.grad)

[[0.25       0.19661193 0.19661193 0.04517666]
 [0.23500371 0.22171287 0.25       0.25      ]]
tensor([[0.2500, 0.1966, 0.1966, 0.0452],
        [0.2350, 0.2217, 0.2500, 0.2500]])


##### ReLU

In [13]:
X = np.array([[0,1,-1,3],[0.5,0.7,0,0]])
X_tensor = torch.tensor([[0.,1.,-1.,3.],[0.5,0.7,0.,0.]], requires_grad=True)

In [14]:
model = ReLU()
Y = model.forward(X)
print(Y)
model_torch = nn.ReLU()
Y_tensor = model_torch(X_tensor)
print(Y_tensor)

[[0.  1.  0.  3. ]
 [0.5 0.7 0.  0. ]]
tensor([[0.0000, 1.0000, 0.0000, 3.0000],
        [0.5000, 0.7000, 0.0000, 0.0000]], grad_fn=<ReluBackward0>)


In [15]:
dX = model.backward(np.ones_like(Y))
Y_tensor.backward(torch.ones_like(Y_tensor))
print(dX)
print(X_tensor.grad)

[[0. 1. 0. 1.]
 [1. 1. 0. 0.]]
tensor([[0., 1., 0., 1.],
        [1., 1., 0., 0.]])


##### Add

In [16]:
X = np.full((10,5),2.)
W = np.full((5,),3.)
X_tensor = torch.full((10,5),2., requires_grad=True)
W_tensor = torch.full((5,),3., requires_grad=True)

In [17]:
model = Add()
Y = model.forward(X,W)
dX,db = model.backward(np.ones_like(Y))
print(dX, db)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] [10. 10. 10. 10. 10.]


In [18]:
Y_tensor = X_tensor+W_tensor
Y_tensor.backward(torch.ones_like(Y_tensor))
print(X_tensor.grad,W_tensor.grad)


tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]) tensor([10., 10., 10., 10., 10.])


##### MulLayer

In [25]:
X = np.full((10,5),2.)
W = np.full((5,1),3.)
X_tensor = torch.full((10,5),2., requires_grad=True)
W_tensor = torch.full((5,1),3., requires_grad=True)

In [26]:
model = Mul()
Y = model.forward(X,W)
Y_tensor = torch.matmul(X_tensor,W_tensor)
print(Y)
print(Y_tensor)


[[30.]
 [30.]
 [30.]
 [30.]
 [30.]
 [30.]
 [30.]
 [30.]
 [30.]
 [30.]]
tensor([[30.],
        [30.],
        [30.],
        [30.],
        [30.],
        [30.],
        [30.],
        [30.],
        [30.],
        [30.]], grad_fn=<MmBackward0>)


In [27]:
dX,dW = model.backward(np.ones_like(Y))
print("dX : ", dX)
print("dW : ", dW)
Y_tensor.backward(torch.ones_like(Y_tensor))
print("dX : ", X_tensor.grad)
print("dW : ", W_tensor.grad)

dX :  [[3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]]
dW :  [[20.]
 [20.]
 [20.]
 [20.]
 [20.]]
dX :  tensor([[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]])
dW :  tensor([[20.],
        [20.],
        [20.],
        [20.],
        [20.]])
